---
version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "/unsafe/*"
      - "/safe/*"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore(dev-deps)
  - package-ecosystem: "npm"
    directories:
      - "/docs"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore(dev-deps)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore(ci-deps)
