---
version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "/unsafe/*"
      - "/safe/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directories:
      - "/docs"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
