---
name: Maven Dependency Check

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

env:
  MAVEN_OPTS: >
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subproject:
          [
            "unsafe/sun-misc-unsafe",
            "unsafe/jdk-internal-misc-unsafe",
            "safe/java-lang-foreign-memorysegment",
          ]
    name: Check dependencies of ${{ matrix.subproject }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: temurin
          java-version: 21
      - name: Dependency Check with Maven
        working-directory: ${{ matrix.subproject }}
        run: |
          # shellcheck disable=SC2086
          ./mvnw ${MAVEN_CLI_OPTS} dependency-check:aggregate
      - name: Clean up
        run: rm "${HOME}/.m2/settings.xml"
